{{- if eq .Values.provider "aws" }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "gateway-plural.fullname" . }}-proxy-protocol
  labels:
  {{- include "gateway-plural.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      {{- include "gateway.selectorLabels" .Subcharts.gateway | nindent 6 }}
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
{{- end }}
