apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
  {{ include "airbyte.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      airbyte.component: metrics
      app: airbyte-metrics
  template:
    metadata:
      labels:
        airbyte.component: metrics
        app: airbyte-metrics
        {{ include "airbyte.labels" . | nindent 8 }}
    spec:
      containers:
      - name: airbyte-metrics
        image: "{{ .Values.global.imageRegistry }}/airbyte/metrics-reporter:{{ .Values.airbyte.version }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: AIRBYTE_VERSION
          value: {{ .Values.airbyte.version }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_DOGSTATSD_PORT
          value: "8125"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.airbyte.externalDatabase.existingSecret }}
              key: {{ .Values.airbyte.externalDatabase.existingSecretPasswordKey }}
        - name: DATABASE_URL
          value: {{ include "airbyte-plural.database.url" . | quote }}
        - name: DATABASE_USER
          value: {{ .Values.airbyte.externalDatabase.user }}
        - name: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
          value: 0.35.15.001
        - name: METRIC_CLIENT
          value: otel
        - name: OTEL_COLLECTOR_ENDPOINT
          value: http://plural-otel-collector.monitoring:4317
        - name: PUBLISH_METRICS
          value: 'true'
