{{- if .Values.airbyte.postgresql.enabled }}
apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: db
  labels:
{{ include "airbyte.labels" . | indent 4 }}
spec:
  type: db
  target: service/airbyte-master
  credentials:
    secret: airbyte.plural-airbyte.credentials.postgresql.acid.zalan.do
    key: password
    user: airbyte
  dbConfig:
    name: airbyte
    engine: postgres
    port: 5432
{{- end }}