apiVersion: v2
name: metabase
description: A Helm chart for Kubernetes
type: application
version: 0.1.15
appVersion: "0.46.6.4"
dependencies:
- name: postgres
  version: 0.1.16
  repository: https://pluralsh.github.io/module-library
  condition: database.operatorEnabled
