apiVersion: v2
name: metabase
description: A Helm chart for Kubernetes
type: application
version: 0.1.9
appVersion: "0.45.1"
dependencies:
- name: postgres
  version: 0.1.10
  repository: https://pluralsh.github.io/module-library
  condition: database.operatorEnabled
