apiVersion: v2
name: retool
description: helm chart for retool
type: application
version: 0.1.12
appVersion: "v3.52.1"
dependencies:
- name: postgres
  version: 0.1.5
  repository: https://pluralsh.github.io/module-library
- name: retool
  version: 6.1.0
  repository: https://charts.retool.com
