apiVersion: v2
name: retool
description: helm chart for retool
type: application
version: 0.1.6
appVersion: "v3.10.2"
dependencies:
- name: postgres
  version: 0.1.5
  repository: https://pluralsh.github.io/module-library
- name: retool
  version: 6.0.0
  repository: https://charts.retool.com
