apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|argo'
  labels:
    application-crd-id: kubeflow-pipelines
  name: argo
  namespace: kubeflow
