apiVersion: v2
name: calendso
description: A Helm chart for Kubernetes
type: application
version: 0.1.14
appVersion: "1.16.0"
dependencies:
- name: postgres
  version: 0.1.4
  repository: https://pluralsh.github.io/module-library