apiVersion: v2
name: argo-workflows
description: A Helm chart for Kubernetes
type: application
version: 0.1.20
appVersion: "v3.2.9"
dependencies:
- name: argo-workflows
  version: 0.13.1
  repository: https://argoproj.github.io/argo-helm
