apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: influx-rules
spec:
  groups:
  - name: influx
    rules:
    - alert: InfluxDbCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"influxdb-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"influxdb-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Influxdb cluster's cpu has gotten too high
        description: the cpu utilization of your influxdb cluster is higher than recommended
    - alert: InfluxDbMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"influxdb-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"influxdb-[0-9]+"})
        )  > 0.5
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Influxdb cluster's memory has gotten too high
        description: the memory utilization of your influxdb cluster is higher than recommended
    - alert: InfluxDbVolumeFull
      expr: |
        avg((kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"influxdb-data-.*"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"influxdb-data-.*"}) / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"influxdb-data-.*"}) > 0.7
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Influxdb's persistent volume is nearly full
        description: you have very little headroom in your influxdb volume, and it should be sized up