apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: scaling-manual
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "influx.labels" . | indent 4 }}
spec:
  name: Influxdb Scaling
  description: overview of how to optimally scale your influxdata deployment
  display: |-
{{ .Files.Get "runbooks/scaling-manual.xml" | indent 4 }}
  datasources:
  - name: influx-cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"influxdb-[0-9]+"}[5m])) by (pod)
  - name: influx-memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"influxdb-[0-9]+"}) by (pod)
  - name: kap-cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"influx-kapacitor-[a-z0-9]+-[a-z0-9]+"}[5m])) by (pod)
  - name: kap-memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"influx-kapacitor-[a-z0-9]+-[a-z0-9]+"}) by (pod)
  - name: chron-cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"influx-chronograf-[a-z0-9]+-[a-z0-9]+"}[5m])) by (pod)
  - name: chron-memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"influx-chronograf-[a-z0-9]+-[a-z0-9]+"}) by (pod)
  - name: influx
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: influxdb
  - name: kap
    type: kubernetes
    kubernetes:
      resource: deployment
      name: influx-kapacitor
  - name: chron
    type: kubernetes
    kubernetes:
      resource: deployment
      name: influx-chronograf
  - name: nodes
    type: nodes
  actions:
  - name: influx-scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - influx
        - influxdb
        - resources
        - requests
        - cpu
        valueFrom: influx-cpu
      - path:
        - influx
        - influxdb
        - resources
        - requests
        - memory
        valueFrom: influx-memory
  - name: kap-scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - influx
        - kapacitor
        - resources
        - requests
        - cpu
        valueFrom: kap-cpu
      - path:
        - influx
        - kapacitor
        - resources
        - requests
        - memory
        valueFrom: kap-memory
  - name: chron-scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - influx
        - chronograf
        - resources
        - requests
        - cpu
        valueFrom: chron-cpu
      - path:
        - influx
        - chronograf
        - resources
        - requests
        - memory
        valueFrom: chron-memory
---
apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: volume-scaling
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "influx.labels" . | indent 4 }}
spec:
  name: Influxdb Volume Scaling
  description: overview of how to optimally scale your influxdata persistent volumes
  display: |-
{{ .Files.Get "runbooks/volume-scaling.xml" | indent 4 }}
  datasources:
  - name: influx-volume
    type: prometheus
    prometheus:
      format: none
      legend: $persistentvolumeclaim
      query: (kubelet_volume_stats_capacity_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"influxdb-data-.*"} - kubelet_volume_stats_available_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"influxdb-data-.*"}) / kubelet_volume_stats_capacity_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"influxdb-data-.*"}
  - name: influx
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: influxdb
  actions:
  - name: volume-scale
    action: config
    redirectTo: '/'
    configuration:
      statefulSets:
      - name: influxdb
        persistentVolume: influxdb-data
        valueFrom: influx-storage
      updates:
      - path: 
        - influx
        - influxdb
        - persistence
        - size
        valueFrom: influx-storage
