apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: scaling-manual
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "mlflow.labels" . | indent 4 }}
spec:
  name: MLFlow Scaling
  description: overview of how to optimally scale your MLFlow cluster
  display: |-
{{ .Files.Get "runbooks/scaling-manual.xml" | indent 4 }}
  datasources:
  - name: mlflow-cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"mlflow.+"}[5m])) by (pod)
  - name: mlflow-memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"mlflow.+"}) by (pod)
  - name: server
    type: kubernetes
    kubernetes:
      resource: deployment
      name: mlflow
  - name: nodes
    type: nodes
  actions:
  - name: scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
        - path:
            - mlflow
            - resources
            - requests
            - cpu
          valueFrom: mlflow-cpu
        - path:
            - mlflow
            - resources
            - requests
            - memory
          valueFrom: mlflow-memory