apiVersion: v2
name: ray
description: helm chart for ray
type: application
version: 0.1.5
appVersion: "2.0.0"
dependencies:
- name: oauth2-proxy
  version: 6.2.7
  repository: https://oauth2-proxy.github.io/manifests
  condition: oauth2-proxy.enabled
