apiVersion: v2
name: prefect-agent
description: helm chart for prefect-agent
type: application
version: 0.1.2
appVersion: v2.10.12
dependencies:
- name: prefect-agent
  version: 2023.06.01
  repository: https://prefecthq.github.io/prefect-helm
  condition: prefect-agent.enabled
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.5
  condition: test-base.enabled