apiVersion: v2
name: prefect-agent
description: helm chart for prefect-agent
type: application
version: 0.1.1
appVersion: v2.7.9
dependencies:
- name: prefect-agent
  version: 2023.05.25
  repository: https://prefecthq.github.io/prefect-helm
  condition: prefect-agent.enabled
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.5
  condition: test-base.enabled