apiVersion: v2
name: temporal
description: helm chart for temporal
type: application
version: 0.1.1
appVersion: "1.21.5"
dependencies:
- name: postgres
  version: 0.2.1
  repository: https://pluralsh.github.io/module-library
- name: temporal
  version: 0.27.2
  repository: https://pluralsh.github.io/plural-helm-charts