apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-statsd-exporter
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.exporter.replicas }}
  selector:
    matchLabels:
      {{- include "statsd-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "statsd-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: statsd-exporter
      securityContext:
        {{- toYaml .Values.exporter.podSecurityContext | nindent 8 }}
      containers:
        - name: statsd
          securityContext:
            {{- toYaml .Values.exporter.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ default .Chart.AppVersion .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          args:
            - --web.listen-address=:{{ .Values.exporter.web.port }}
            - --web.telemetry-path={{ .Values.exporter.web.path }}
            {{- if .Values.exporter.statsd.udpPort }}
            - --statsd.listen-udp=:{{ .Values.exporter.statsd.udpPort }}
            {{- else }}
            - --statsd.listen-udp=
            {{- end }}
            {{- if .Values.exporter.statsd.tcpPort }}
            - --statsd.listen-tcp=:{{ .Values.exporter.statsd.tcpPort }}
            {{- else }}
            - --statsd.listen-tcp=
            {{- end }}
            - --statsd.cache-size={{ .Values.exporter.statsd.cacheSize }}
            - --statsd.event-queue-size={{ .Values.exporter.statsd.eventQueueSize }}
            - --statsd.event-flush-threshold={{ .Values.exporter.statsd.eventFlushThreshold }}
            - --statsd.event-flush-interval={{ .Values.exporter.statsd.eventFlushInterval }}
            - --statsd.mapping-config=/etc/prometheus-statsd-exporter/statsd-mapping.conf
          ports:
            - name: web
              containerPort: {{ .Values.exporter.web.port }}
              protocol: TCP
            {{- if .Values.exporter.statsd.tcpPort }}
            - name: statsd-tcp
              containerPort: {{ .Values.exporter.statsd.tcpPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.exporter.statsd.udpPort }}
            - name: statsd-udp
              containerPort: {{ .Values.exporter.statsd.udpPort }}
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.exporter.web.path }}
              port: web
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
          volumeMounts:
          - name: statsd-mapping-config
            mountPath: /etc/prometheus-statsd-exporter
      volumes:
      - name: statsd-mapping-config
        configMap:
          name: statsd-exporter-config
          items:
          - key: statsd.mappingConf
            path: statsd-mapping.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-exporter-config
  labels:
{{ include "hasura.labels" . | indent 4 }}
data:
  statsd.mappingConf: {{ .Files.Get "files/statsd-mapping.conf" | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statsd-exporter
  labels:
{{ include "hasura.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
  {{- include "statsd-exporter.selectorLabels" . | nindent 4 }}
  {{- with .Values.exporter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - port: {{ .Values.exporter.web.port }}
      targetPort: web
      protocol: TCP
      name: web
    {{- if .Values.exporter.statsd.tcpPort }}
    - port: {{ .Values.exporter.statsd.tcpPort }}
      targetPort: statsd-tcp
      protocol: TCP
      name: statsd-tcp
    {{- end }}
    {{- if .Values.exporter.statsd.udpPort }}
    - port: {{ .Values.exporter.statsd.udpPort }}
      targetPort: statsd-udp
      protocol: UDP
      name: statsd-udp
    {{- end }}
  selector:
    {{- include "statsd-exporter.selectorLabels" . | nindent 4 }}