apiVersion: v2
name: strapi
description: helm chart for strapi
type: application
version: 0.1.0
appVersion: "4.2.0"

dependencies:
- name: postgres
  version: 0.1.5
  repository: https://pluralsh.github.io/module-library
