apiVersion: v2
name: clickhouse
description: helm chart for clickhouse
type: application
version: 0.1.3
appVersion: 0.21.2
dependencies:
- name: altinity-clickhouse-operator
  version: 0.21.2
  repository: https://raw.githubusercontent.com/Altinity/clickhouse-operator/gh-pages
