apiVersion: v2
name: directus
description: helm chart for directus
type: application
version: 0.1.0
appVersion: 9.24.0
dependencies:
  - name: postgres
    version: 0.1.16
    repository: https://pluralsh.github.io/module-library
    condition: postgres.enabled