apiVersion: v2
name: cube
description: helm chart for cube
type: application
version: 0.1.6
appVersion: "v0.33.30"
dependencies:
- name: cube
  version: 2.0.1
  repository: https://gadsme.github.io/charts
- name: cubestore
  version: 0.9.2
  repository: https://gadsme.github.io/charts
