apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
  {{ include "sentry-plural.labels" . | nindent 4 }}
  name: sentry-rules
spec:
  groups:
  - name: sentry
    rules:
    - alert: SentryPostgresCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-sentry-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-sentry-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural sentry dbs's cpu has gotten too high
        description: the cpu utilization of your plural sentry is higher than recommended
    - alert: SentryPostgresMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-sentry-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-sentry-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: sentry db's memory has gotten too high
        description: the memory utilization of your plural sentry db is higher than recommended
    