dependencies:
- name: aws-bootstrap
  repo: bootstrap
  type: terraform
  version: '>= 0.1.1'
  optional: true
- name: azure-bootstrap
  repo: bootstrap
  type: terraform
  version: '>= 0.1.1'
  optional: true
- name: gcp-bootstrap
  repo: bootstrap
  type: terraform
  version: '>= 0.1.1'
  optional: true
- name: equinix-bootstrap
  repo: bootstrap
  type: terraform
  version: '>= 0.1.1'
  optional: true
- name: kind-bootstrap
  repo: bootstrap
  type: terraform
  version: '>= 0.1.0'
  optional: true
providers:
- aws
- gcp
- azure
- equinix
- kind
description: grafana kubernetes setup 
version: 0.1.0
