apiVersion: v2
name: lightdash
description: helm chart for lightdash
type: application
version: 0.1.4
appVersion: "v0.138.0"
dependencies:
  - name: lightdash
    version: 0.7.1
    repository: https://lightdash.github.io/helm-charts
  - name: postgres
    version: 0.1.17
    repository: https://pluralsh.github.io/module-library
