{{ if eq .Values.provider "azure" }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: console
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  resourceID: {{ .Values.consoleIdentityId }}
  clientID: {{ .Values.consoleIdentityClientId }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: console-binding
spec:
  azureIdentity: console
  selector: console
{{ end }}