apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: console-rules
spec:
  groups:
  - name: console
    rules:
    - alert: ConsoleCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"console-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"console-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Console deployment's cpu has gotten too high
        description: the cpu utilization of your console deployment is higher than recommended
    - alert: ConsoleMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"console-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"console-[0-9]+"})
        )  > 0.5
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Console deployment's memory has gotten too high
        description: the memory utilization of your console deployment is higher than recommended
    - alert: ConsoleDbCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-console-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-console-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Console's postgres cpu has gotten too high
        description: the cpu utilization of your console deployment's postgres db is higher than recommended
    - alert: ConsoleDbMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-console-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-console-[0-9]+"})
        )  > 0.6
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Console postgres memory has gotten too high
        description: the memory utilization of your console deployment's postgres db is higher than recommended

    