apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: db-scaling
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "console.labels" . | indent 4 }}
spec:
  name: Postgres Scaling
  description: overview of how to accurately scale console's postgres instance
  alerts:
  - name: ConsoleDbCPU
  - name: ConsoleDbMEM
  display: |-
{{ .Files.Get "runbooks/db-scaling.xml" | indent 4 }}
  datasources:
  - name: cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-console-[0-9]+"}[5m])) by (pod)
  - name: memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-console-[0-9]+"}) by (pod)
  - name: statefulset
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: plural-console
  - name: nodes
    type: nodes
  actions:
  - name: scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - console
        - postgres
        - resources
        - requests
        - cpu
        valueFrom: cpu
      - path:
        - console
        - postgres
        - resources
        - requests
        - memory
        valueFrom: memory
      - path:
        - console
        - postgres
        - replicas
        valueFrom: replicas
---
apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: scaling-manual
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "console.labels" . | indent 4 }}
spec:
  name: Console Scaling
  description: overview of how to accurately scale console deployment
  alerts:
  - name: ConsoleCPU
  - name: ConsoleMEM
  display: |-
{{ .Files.Get "runbooks/scaling.xml" | indent 4 }}
  datasources:
  - name: cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"console-[0-9]+"}[5m])) by (pod)
  - name: memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"console-[0-9]+"}) by (pod)
  - name: statefulset
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: console
  - name: nodes
    type: nodes
  actions:
  - name: scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - console
        - resources
        - requests
        - cpu
        valueFrom: cpu
      - path:
        - console
        - resources
        - requests
        - memory
        valueFrom: memory