apiVersion: v1
kind: Secret
metadata:
  name: console-env
  labels:
{{ include "console.labels" . | indent 4 }}
type: Opaque
data:
  PROVIDER: {{ .Values.provider | b64enc | quote }}
  CLUSTER_NAME: {{ .Values.secrets.cluster_name | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwt | b64enc | quote }}
  GIT_URL: {{ .Values.secrets.git_url | b64enc | quote }}
  REPO_ROOT: {{ .Values.secrets.repo_root | b64enc | quote }}
  BRANCH_NAME: {{ .Values.secrets.branch_name | b64enc | quote }}
{{ if .Values.secrets.webhook_secret }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhook_secret | b64enc | quote }}
{{ end }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
  GIT_USER: {{ .Values.secrets.git_user | b64enc | quote }}
  GIT_EMAIL: {{ .Values.secrets.git_email | b64enc | quote }}
{{ if .Values.secrets.git_access_token }}
  GIT_ACCESS_TOKEN: {{ .Values.secrets.git_access_token | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.ssh_passphrase }}
  SSH_PASSPHRASE: {{ .Values.secrets.ssh_passphrase | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.piazza_webhook_secret }}
  PIAZZA_WEBHOOK_SECRET: {{ .Values.secrets.piazza_webhook_secret | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.id_rsa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: console-ssh
  labels:
{{ include "console.labels" . | indent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.secrets.id_rsa | b64enc | quote }}
  id_rsa.pub: {{ .Values.secrets.id_rsa_pub | b64enc | quote }}
  known_hosts: {{ .Values.secrets.known_hosts | b64enc | quote }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: console-conf
  labels:
{{ include "console.labels" . | indent 4 }}
type: Opaque
data:
  config.yml: {{ .Values.secrets.config | b64enc | quote }}
  key: {{ .Values.secrets.key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: console-migration-env
  labels:
{{ include "console.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_NAME: {{ .Values.secrets.admin_name | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.admin_email | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.admin_password | b64enc | quote }}