apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys filecoin crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: helm
    name: efs-csi-driver
    repo: bootstrap
    version: '>= 0.1.4'
  - type: terraform
    name: aws
    repo: filecoin
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: azure
    repo: filecoin
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: filecoin
    version: '>= 0.1.0'
    optional: true
