apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes
type: application
version: 0.1.4
appVersion: "1.16.0"
dependencies:
- name: strimzi-kafka-operator
  version: 0.24.0
  repository: https://strimzi.io/charts/