strimzi-kafka-operator:
  watchAnyNamespace: true
  defaultImageRegistry: dkr.plural.sh
  defaultImageRepository: kafka/strimzi
  defaultImageTag: 0.24.0
  resources:
    limits:
      memory: 384Mi
    requests:
      memory: 384Mi
      cpu: 20m
  # image:
  #   registry: dkr.plural.sh
  #   repository: kafka/strimzi/operator
  #   name: ""
  #   tag: 0.24.0

create: true

kafkaVolumes:
  "0":
    type: persistent-claim
    size: 100Gi
    deleteClaim: false

kafka:
  replicas: 3
  version: 2.8.0
  storage:
    type: jbod
  additionalListeners: []
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    log.message.format.version: "2.8"
    inter.broker.protocol.version: "2.8"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 1Gi
      cpu: ""

entityOperator:
  topicOperator: {}
  userOperator: {}

zookeeper:
  replicas: 3
  resources:
    requests:
      cpu: 10m
      memory: 400Mi
    limits:
      memory: 400Mi
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: zookeeper-metrics-config.yml

schema-registry:
  enabled: true
  image:
    registry: dkr.plural.sh
    repository: kafka/bitnami/schema-registry
    tag: 7.2.2
  resources:
    requests:
      cpu: 20m
      memory: 280Mi
    limits:
      memory: 400Mi
  kafka:
    enabled: false
  externalKafka:
    brokers:
      - PLAINTEXT://kafka-kafka-bootstrap.kafka.svc:9092
