apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
  {{ include "cluster-operator.labels" . | nindent 4 }}
  name: rabbitmq-rules
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitmqCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"rabbitmq-server-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"rabbitmq-server-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: rabbitmq's cpu has gotten too high
        description: the cpu utilization of your rabbitmq cluster is higher than recommended
    - alert: RabbitmqMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"rabbitmq-server-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"rabbitmq-server-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: rabbitmq's memory has gotten too high
        description: the memory utilization of your rabbitmq cluster is higher than recommended
    