apiVersion: v2
name: kratos
description: helm chart for kratos
type: application
version: 0.1.13
appVersion: "v1.0.0"
dependencies:
- name: postgres
  version: 0.1.5
  repository: https://pluralsh.github.io/module-library
- name: kratos
  repository: https://k8s.ory.sh/helm/charts
  version: 0.21.8