---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: pvcviewers.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: PVCViewer
    listKind: PVCViewerList
    plural: pvcviewers
    singular: pvcviewer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PVCViewer is the Schema for the pvcviewers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PVCViewerSpec defines the desired state of PVCViewer
            properties:
              pvcname:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                type: string
              viewerimage:
                type: string
            required:
            - pvcname
            - viewerimage
            type: object
          status:
            description: PVCViewerStatus defines the observed state of PVCViewer
            properties:
              conditions:
                description: Conditions is an array of current conditions
                items:
                  description: PVCViewerCondition defines the observed state of PVCViewer
                  properties:
                    deploymentState:
                      description: Deployment status, 'Available', 'Progressing',
                        'ReplicaFailure' .
                      type: string
                    lastProbeTime:
                      description: Last time we probed the condition.
                      format: date-time
                      type: string
                  required:
                  - deploymentState
                  type: object
                type: array
              ready:
                type: boolean
              readyReplicas:
                description: ReadyReplicas defines the number of PVCViewer Servers
                  that are available to connect. The value of ReadyReplicas can be
                  either 0 or 1
                format: int32
                type: integer
            required:
            - conditions
            - ready
            - readyReplicas
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
