apiVersion: v2
name: influx
description: A Helm chart for Kubernetes
type: application
version: 0.1.22
appVersion: "1.16.0"
dependencies:
- name: chronograf
  version: 1.1.24
  repository: https://helm.influxdata.com/
  condition: chronograf.enabled
- name: kapacitor
  version: 1.3.3
  repository: file://../../../../influxdata-helm-charts/charts/kapacitor
  condition: kapacitor.enabled
- name: telegraf-ds
  version: 1.0.22
  repository: https://helm.influxdata.com/
  condition: telegraf.enabled
- name: telegraf
  version: 1.8.6
  repository: https://helm.influxdata.com/
  condition: telegraf.enabled
- name: telegraf-operator
  version: 1.3.0
  repository: https://helm.influxdata.com/
  condition: telegraf.enabled
- name: influxdb
  version: 4.10.0
  repository: https://helm.influxdata.com/