apiVersion: v2
name: n8n
description: helm chart for n8n
type: application
version: 0.1.4
appVersion: "0.181.2"
dependencies:
- name: postgres
  version: 0.1.10
  repository: https://pluralsh.github.io/module-library
