apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys sentry crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: helm
    name: postgres
    repo: postgres
    version: '>= 0.1.6'
  - type: helm
    name: cluster-operator
    repo: rabbitmq
    version: '>= 0.1.8'
  - type: helm
    name: redis
    repo: redis
    version: '>= 0.1.1'
  - type: terraform
    name: aws
    repo: sentry
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: azure
    repo: sentry
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: gcp
    repo: sentry
    version: '>= 0.1.1'
    optional: true