apiVersion: v2
name: chatwoot
description: Open-source customer engagement suite, an alternative to Intercom, Zendesk, Salesforce Service Cloud etc.
type: application
version: 0.1.11
appVersion: v3.3.1
dependencies:
- name: chatwoot
  version: 1.1.4
  repository: https://chatwoot.github.io/charts
- name: postgres
  version: 0.1.12
  repository: https://pluralsh.github.io/module-library
