apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.13
appVersion: "1.5.1"
dependencies:
- name: ingress-nginx
  version: 4.5.2
  repository: https://kubernetes.github.io/ingress-nginx
