apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.15
appVersion: "1.7.0"
dependencies:
- name: ingress-nginx
  version: 4.6.0
  repository: https://kubernetes.github.io/ingress-nginx
