apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: v2.8.4
dependencies:
- name: config-overlays
  version: 0.1.1
  repository: https://pluralsh.github.io/module-library
- name: argo-cd
  version: 5.46.7
  repository: https://argoproj.github.io/argo-helm
- name: argocd-image-updater
  version: 0.9.1
  repository: https://argoproj.github.io/argo-helm
  condition: argocd-image-updater.enabled
