apiVersion: v2
name: tempo
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "2.4.0"
dependencies:
- name: tempo-distributed
  version: 1.9.0
  repository: https://grafana.github.io/helm-charts
