apiVersion: v2
name: crossplane
description: A Helm chart for Kubernetes
type: application
version: 0.1.8
appVersion: "1.3.0"
dependencies:
- name: crossplane
  version: 1.3.0
  repository: https://charts.crossplane.io/stable
