apiVersion: v2
name: oauth2-proxy
description: A chart bundling oauth2-proxy for plural
type: application
version: 0.1.12
appVersion: "7.1.3"
dependencies:
- name: oauth2-proxy
  version: 4.1.0
  repository: https://oauth2-proxy.github.io/manifests
