apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/serving-cert
  labels:
    app: kfserving
    app.kubernetes.io/name: kfserving
  name: inferenceservice.serving.kubeflow.org
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: kfserving-webhook-server-service
        namespace: kubeflow
        path: /validate-serving-kubeflow-org-v1alpha2-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kfserving-webhook-server.validator
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
  - clientConfig:
      caBundle: Cg==
      service:
        name: kfserving-webhook-server-service
        namespace: kubeflow
        path: /validate-serving-kubeflow-org-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kfserving-webhook-server.v1beta1.validator
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/serving-cert
  labels:
    app: kfserving
    app.kubernetes.io/name: kfserving
  name: trainedmodel.serving.kubeflow.org
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: kfserving-webhook-server-service
        namespace: kubeflow
        path: /validate-serving-kubeflow-org-v1alpha1-trainedmodel
    failurePolicy: Fail
    name: trainedmodel.kfserving-webhook-server.validator
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels
