apiVersion: v2
name: elasticsearch
description: A Helm chart for Kubernetes
type: application
version: 0.1.12
appVersion: "2.8.0"
dependencies:
- name: eck-operator
  version: 2.8.0
  repository: https://helm.elastic.co
  #https://github.com/elastic/cloud-on-k8s/tree/main/deploy
