apiVersion: v2
name: elasticsearch
description: A Helm chart for Kubernetes
type: application
version: 0.1.6
appVersion: "1.6.0"
dependencies:
- name: eck-operator
  version: 1.6.0
  repository: https://helm.elastic.co
