apiVersion: v2
name: jupyterhub
description: helm chart for jupyterhub
type: application
version: 0.1.2
appVersion: "3.1.1"
maintainers:
  - name: Samuel Gordalina
    email: samuel.gordalina@gmail.com
dependencies:
  - name: jupyterhub
    version: 3.0.12
    repository: https://charts.bitnami.com/bitnami
