apiVersion: v2
name: jupyterhub
description: helm chart for jupyterhub
type: application
version: 0.1.4
appVersion: "3.1.1"
maintainers:
  - name: Samuel Gordalina
    email: samuel.gordalina@gmail.com
dependencies:
  - name: jupyterhub
    version: 2.0.0
    repository: https://jupyterhub.github.io/helm-chart/
  - name: postgres
    version: 0.1.17
    repository: https://pluralsh.github.io/module-library
    condition: postgres.enabled