apiVersion: v2
name: grafana
description: A Helm chart for grafana on plural
type: application
version: 0.1.10
appVersion: "8.0.5"
dependencies:
- name: grafana
  version: 6.14.2
  repository: https://grafana.github.io/helm-charts
