apiVersion: v2
name: grafana
description: A Helm chart for grafana on plural
type: application
version: 0.2.13
appVersion: "8.3.2"
dependencies:
- name: grafana
  version: 6.29.5
  repository: https://grafana.github.io/helm-charts
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.3
  condition: test-base.enabled