apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: {{ .Values.istio.namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls-egress
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: ISTIO_MUTUAL
