{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kas.serviceName" . }}
  labels:
    {{- include "kas.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "kas.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: http-metrics
      path: {{ .Values.metrics.path }}
    {{- with .Values.metrics.serviceMonitor.endpointConfig }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end -}}
