apiVersion: v2
name: kubecost
description: chart for deploy kubecost
type: application
version: 0.1.18
appVersion: "1.85.1"
dependencies:
- name: cost-analyzer
  version: 1.90.0
  repository: https://kubecost.github.io/cost-analyzer/
