
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-server
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      airbyte: server
  strategy:
    type: Recreate # Needed due to volume claims
  template:
    metadata:
      labels:
        airbyte: server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
      {{- if .Values.server.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.server.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.server.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
      - name: airbyte-server-container
        image: {{ include "airbyte.serverImage" . }}
        imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
        envFrom:
        - secretRef:
            name: airbyte-env
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "airbyte.postgresql.secretName" . }}
              key: {{ include "airbyte.database.existingsecret.key" . }}
        - name: LOG_LEVEL
          value: "{{ .Values.scheduler.log.level }}"
        {{- if .Values.server.extraEnv }}
        {{ .Values.server.extraEnv | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.server.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.server.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8001
          protocol: TCP
        {{- if .Values.server.resources }}
        resources: {{- toYaml .Values.server.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: airbyte-data
          mountPath: /configs
          subPath: configs
        - name: airbyte-data
          mountPath: /workspace
          subPath: workspace
        - name: gcs-log-creds-volume
          mountPath: /secrets/gcs-log-creds
          readOnly: true
      volumes:
      - name: airbyte-data
        persistentVolumeClaim:
          claimName: {{ include "common.names.fullname" . }}-data
      - name: gcs-log-creds-volume
        secret:
          secretName: {{ default "gcs-log-creds" .Values.gcpCredentialsSecret }}
