apiVersion: v2
name: ingress-nginx-private
description: A Helm chart for Kubernetes
type: application
version: 0.1.17
appVersion: "1.1.0"
dependencies:
- name: ingress-nginx
  version: 4.0.17
  repository: https://kubernetes.github.io/ingress-nginx
