apiVersion: v2
name: dex
description: Dex idp packaged for deployment on plural
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: dex
  version: 0.4.0
  repository: https://charts.dexidp.io