apiVersion: v2
name: airbyte
description: Unified data integration platform
type: application
version: 0.2.21
appVersion: "1.16.0"
dependencies:
  - name: airbyte
    version: 0.3.0
  - name: oidc-config
    version: 0.1.6
    repository: https://pluralsh.github.io/module-library
    condition: oidc-config.enabled
  - name: test-base
    repository: https://pluralsh.github.io/module-library
    version: 0.1.3
    condition: test-base.enabled
