---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-controller-role
  labels:
    plural.sh/name: dash-controller
rules:
- apiGroups: ["dash.plural.sh"]
  resources: ["dashapplications", "dashapplications/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["events", "services"]
  verbs: ["list", "watch", "create", "update", "patch", "get", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-controller
  labels:
    plural.sh/name: dash-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "dash-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dash-controller-role
  apiGroup: rbac.authorization.k8s.io
