apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{ include "gitlab-plural.labels" . | nindent 4 }}
  name: gitlab-rules
spec:
  groups:
  - name: gitlab
    rules:
    - alert: GitlabPostgresCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-gitlab-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-gitlab-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural gitlab dbs's cpu has gotten too high
        description: the cpu utilization of your gitlab postgres db is higher than recommended
    - alert: GitlabPostgresMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-gitlab-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-gitlab-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: gitlab db's memory has gotten too high
        description: the memory utilization of your gitlab postgres db is higher than recommended
    - alert: GitlabGitalyCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-gitaly-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-gitaly-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: gitlab gitaly cluster cpu has gotten too high
        description: the cpu utilization of your gitlab gitalay cluster is higher than recommended
    - alert: GitlabGitalyMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-gitaly-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-gitaly-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: gitlab gitaly cluster memory utilization has gotten too high
        description: the memory utilization of your gitlab gitaly cluster is higher than recommended
    