apiVersion: v2
name: yatai
description: helm chart for yatai
type: application
version: 0.1.0
appVersion: "v1.1.9"
dependencies:
- name: postgres
  version: 0.2.1
  repository: https://pluralsh.github.io/module-library
- name: yatai
  version: 1.1.9
  repository: https://bentoml.github.io/helm-charts
- name: yatai-deployment
  version: 1.1.11
  repository: https://bentoml.github.io/helm-charts
- name: yatai-deployment-crds
  version: 1.1.11
  repository: https://bentoml.github.io/helm-charts
- name: yatai-image-builder
  version: 1.1.4
  repository: https://bentoml.github.io/helm-charts
- name: yatai-image-builder-crds
  version: 1.1.4
  repository: https://bentoml.github.io/helm-charts
