apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
  {{ include "redis.labels" . | nindent 4 }}
  name: redis-rules
spec:
  groups:
  - name: redis
    rules:
    - alert: RedisMasterCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"redis-master-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"redis-master-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: redis master's cpu has gotten too high
        description: the cpu utilization of your redis master cluster is higher than recommended
    - alert: RedisMasterMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"redis-master-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"redis-master-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: redis master's memory has gotten too high
        description: the memory utilization of your redis master cluster is higher than recommended
    - alert: RedisReplicasCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"redis-replicas-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"redis-replicas-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: redis replicas' cpu has gotten too high
        description: the cpu utilization of your redis replicas cluster is higher than recommended
    - alert: RedisReplicasMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"redis-replicas-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"redis-replicas-[0-9]+"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: redis replicas' memory has gotten too high
        description: the memory utilization of your redis replicas cluster is higher than recommended
    