apiVersion: v2
name: dagster
description: A Helm chart for Kubernetes
type: application
version: 0.1.51
appVersion: 1.7.12
dependencies:
- name: postgres
  version: 0.1.16
  repository: https://pluralsh.github.io/module-library
- name: oidc-config
  version: 0.1.7
  repository: https://pluralsh.github.io/module-library
  condition: oidc-config.enabled
- name: dagster
  version: 1.7.12
  repository: https://dagster-io.github.io/helm
- name: config-overlays
  version: 0.1.1
  repository: https://pluralsh.github.io/module-library
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.10
  condition: test-base.enabled
