apiVersion: v2
name: dagster
description: A Helm chart for Kubernetes
type: application
version: 0.1.18
appVersion: 0.15.6
dependencies:
- name: postgres
  version: 0.1.7
  repository: https://pluralsh.github.io/module-library
- name: dagster
  version: 0.15.6
  repository: https://dagster-io.github.io/helm
