apiVersion: v2
name: dagster
description: A Helm chart for Kubernetes
type: application
version: 0.1.42
appVersion: 1.3.5
dependencies:
- name: postgres
  version: 0.1.16
  repository: https://pluralsh.github.io/module-library
- name: dagster
  version: 1.3.5
  repository: https://dagster-io.github.io/helm
- name: config-overlays
  version: 0.1.1
  repository: https://pluralsh.github.io/module-library
