apiVersion: v2
name: kserve
description: helm chart for kserve
type: application
version: 0.1.4
appVersion: "v0.8.0"
dependencies:
- name: kserve
  version: 0.8.0
  repository: https://pluralsh.github.io/plural-helm-charts
