apiVersion: v2
name: oncall
description: helm chart for oncall
type: application
version: 0.1.11
appVersion: "v1.0.49"
dependencies:
- name: postgres
  version: 0.1.10
  repository: https://pluralsh.github.io/module-library
- name: rabbitmq
  version: 0.1.0
  repository: https://pluralsh.github.io/module-library
- name: oncall
  version: 1.0.11
  repository: https://pluralsh.github.io/plural-helm-charts
