apiVersion: v2
name: gitlab
description: A Helm chart for gitlab on plural
type: application
version: 0.3.22
appVersion: 14.0.1

dependencies:
- name: gitlab
  version: 5.0.1
  repository: https://charts.gitlab.io/