apiVersion: v2
appVersion: "1.0"
description: A helm chart for installing plural
name: plural
sources:
- https://github.com/pluralsh/plural
maintainers:
- name: michaeljguarino
  email: mjg@plural.sh
version: 0.7.28

dependencies:
- name: hydra
  version: 0.16.0
  repository: https://k8s.ory.sh/helm/charts