apiVersion: v2
name: grafana-tempo
description: A Helm chart for Kubernetes
type: application
version: 0.1.13
appVersion: "1.1.0"
dependencies:
- name: tempo-distributed
  version: 0.9.16
  repository: https://pluralsh.github.io/plural-helm-charts
