apiVersion: v2
name: datahub
description: helm chart for datahub
type: application
version: 0.1.17
appVersion: v0.10.3
dependencies:
- name: datahub
  version: 0.2.166
  repository: https://pluralsh.github.io/plural-helm-charts
- name: postgres
  version: 0.1.17
  repository: https://pluralsh.github.io/module-library
