apiVersion: v2
name: datahub
description: helm chart for datahub
type: application
version: 0.1.10
appVersion: v0.9.0
dependencies:
- name: datahub
  version: 0.2.109
  repository: "https://helm.datahubproject.io"
- name: postgres
  version: 0.1.7
  repository: https://pluralsh.github.io/module-library
