apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: prometheus-rules
spec:
  groups:
  - name: prometheus
    rules:
    - alert: PrometheusCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"prometheus-monitoring-prometheus-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"prometheus-monitoring-prometheus-[0-9]+", resource="cpu"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: prometheus cluster's cpu has gotten too high
        description: the cpu utilization of your prometheus cluster is higher than recommended
    - alert: PrometheusMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"prometheus-monitoring-prometheus-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"prometheus-monitoring-prometheus-[0-9]+"})
        )  > 1.1
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: prometheus cluster's memory has gotten too high
        description: the memory utilization of your prometheus cluster is higher than recommended
    - alert: PrometheusVolumeFull
      expr: |
        avg(
          (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"prometheus-monitoring-prometheus-.*"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"prometheus-monitoring-prometheus-.*"}) / 
          kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"prometheus-monitoring-prometheus-.*"}
        ) > 0.7
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: prometheus's persistent volume is nearly full
        description: you have very little headroom in your prometheus volume, and it should be sized up
  - name: loki
    rules:
    - alert: LokiCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"monitoring-loki-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"monitoring-loki-[0-9]+", resource="cpu"})
        )  > 0.7
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: loki cluster's cpu has gotten too high
        description: the cpu utilization of your loki cluster is higher than recommended
    - alert: LokiMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"monitoring-loki-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"monitoring-loki-[0-9]+"})
        )  > 0.9
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: loki cluster's memory has gotten too high
        description: the memory utilization of your loki cluster is higher than recommended
    - alert: LokiVolumeFull
      expr: |
        avg(
          (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"monitoring-loki-.*"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"monitoring-loki-.*"}) / 
          kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"monitoring-loki-.*"}
        ) > 0.7
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: loki's persistent volume is nearly full
        description: you have very little headroom in your loki volume, and it should be sized up