apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: db-scaling
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "superset.labels" . | indent 4 }}
spec:
  name: Postgres Scaling
  description: overview of how to accurately scale superset's postgres instance
  alerts:
  - name: SupersetPostgresCPU
  - name: SupersetPostgresMEM
  display: |-
{{ .Files.Get "runbooks/db-scaling.xml" | indent 4 }}
  datasources:
  - name: cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-superset-[0-9]+"}[5m])) by (pod)
  - name: memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-superset-[0-9]+"}) by (pod)
  - name: statefulset
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: plural-superset
  - name: nodes
    type: nodes
  actions:
  - name: scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - superset
        - postgres
        - resources
        - requests
        - cpu
        valueFrom: cpu
      - path:
        - superset
        - postgres
        - resources
        - requests
        - memory
        valueFrom: memory
      - path:
        - superset
        - postgres
        - replicas
        valueFrom: replicas