name: docker

on:
  push:
    branches: [ main ]
jobs:
  docker-postgres:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform@pluralsh.iam.gserviceaccount.com'
        token_format: 'access_token'
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Login to gcr
      run: gcloud auth configure-docker -q
    - name: Login to plural registry
      uses: docker/login-action@v1
      with:
        registry: dkr.plural.sh
        username: mjg@plural.sh
        password: ${{ secrets.PLURAL_ACCESS_TOKEN }}
    - run: |
        docker build -f postgres/Dockerfile -t gcr.io/pluralsh/acid/spilo-13:2.0-p7 -t dkr.plural.sh/postgres/acid/spilo-13:2.0-p7 .
        docker push gcr.io/pluralsh/acid/spilo-13:2.0-p7
        docker push dkr.plural.sh/postgres/acid/spilo-13:2.0-p7
  docker-sentry:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform@pluralsh.iam.gserviceaccount.com'
        token_format: 'access_token'
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Login to gcr
      run: gcloud auth configure-docker -q
    - name: Login to plural registry
      uses: docker/login-action@v1
      with:
        registry: dkr.plural.sh
        username: mjg@plural.sh
        password: ${{ secrets.PLURAL_ACCESS_TOKEN }}
    - run: |
        docker build -f sentry/Dockerfile -t gcr.io/pluralsh/getsentry/sentry:21.5.1-extended -t dkr.plural.sh/sentry/sentry:21.5.1-extended .
        docker push gcr.io/pluralsh/getsentry/sentry:21.5.1-extended
        docker push dkr.plural.sh/sentry/sentry:21.5.1-extended
  docker-airflow:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform@pluralsh.iam.gserviceaccount.com'
        token_format: 'access_token'
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Login to gcr
      run: gcloud auth configure-docker -q
    - name: Login to plural registry
      uses: docker/login-action@v1
      with:
        registry: dkr.plural.sh
        username: mjg@plural.sh
        password: ${{ secrets.PLURAL_ACCESS_TOKEN }}
    - run: |
        docker build -t gcr.io/pluralsh/apache/airflow:2.1.4-python3.8-plrl-2 -t dkr.plural.sh/airflow/apache/airflow:2.1.4-python3.8-plrl-2 airflow
        docker push gcr.io/pluralsh/apache/airflow:2.1.4-python3.8-plrl-2
        docker push dkr.plural.sh/airflow/apache/airflow:2.1.4-python3.8-plrl-2
  