apiVersion: v2
name: vaultwarden
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "1.21.0"
dependencies:
- name: vaultwarden
  version: 0.1.0
  repository: https://pluralsh.github.io/plural-helm-charts
