apiVersion: v2
name: airflow
description: A Helm chart for airflow deployable on plural
type: application
version: 0.3.35
appVersion: "2.6.0"
sources:
  - https://github.com/pluralsh/plural-artifacts/airflow/helm/airflow
maintainers:
  - name: michaeljguarino
    email: mjg@plural.sh
dependencies:
- name: config-overlays
  version: 0.1.1
  repository: https://pluralsh.github.io/module-library
- name: airflow
  version: 8.7.2
  repository: https://pluralsh.github.io/plural-helm-charts
- name: postgres
  version: 0.1.16
  repository: https://pluralsh.github.io/module-library
  condition: postgres.enabled
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.3
  condition: test-base.enabled
