apiVersion: v2
name: airflow
description: A Helm chart for airflow deployable on plural
type: application
version: 0.2.3
appVersion: "1.16.0"
sources:
- https://github.com/pluralsh/plural-artifacts/airflow/helm/airflow
maintainers:
- name: michaeljguarino
  email: mjg@plural.sh
dependencies:
- name: airflow
  version: 8.1.1
  repository: https://airflow-helm.github.io/charts